# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Netium X-Tech Space 
email: zb.public@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  This is Netium's computer technology sharing space.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://netium.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username: netium

# Build settings
markdown: kramdown
